# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Confident Corn
#email: your-email@example.com
#author:
#    name: Gazman Dev LLC
#    email: ilya@gazman.dev
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to our news website! Our AI-generated news articles use ChatGPT to craft unique content based on trends, topics, and news from various sources on the web. While the inspiration is derived from real-world events, the articles themselves are original and not direct copies from any source. This ensures you receive up-to-date and accurate business and economic news, along with unique AI predictions for each piece. Our coverage is unbiased, as our articles are not influenced by human biases, ensuring transparency and integrity in all our reporting. Stay informed and make smarter decisions with our reliable and innovative news platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://confident-corn.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

paginate: 20
paginate_path: page/:num/

header_pages:
  - contact.md
  - about.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
